use regex::Regex;
use serde_json::Value;

use crate::analysis::enforce::enforce_rule_package;
use crate::analysis::prompt::build_rule_prompt;
use crate::analysis::{
    extract_fields, extract_header_alias, extract_string_array,
};
use crate::models::{AnalyzeRulesRequest, RuleAnalysisBasis, RuleAnalysisPackage};

/// Detects the structural pattern of the selected text.
pub(crate) fn detect_structure_guess(selected_text: &str) -> String {
    if selected_text.contains('|') || selected_text.contains('\t') {
        return "table_like".to_string();
    }
    let step_regex = Regex::new(r"(?m)^\s*(Step\s*\d+|\d+[.)])").unwrap();
    if step_regex.is_match(selected_text) {
        return "step_sequence".to_string();
    }
    "section_paragraph".to_string()
}

/// Builds the analysis basis metadata from the request payload.
pub(crate) fn build_rule_analysis_basis(
    payload: &AnalyzeRulesRequest,
    fields: &[String],
    prompt_text: &str,
) -> RuleAnalysisBasis {
    let template_scene_id = payload
        .template
        .get("scene_id")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let template_scene_name = payload
        .template
        .get("scene_name")
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let template_version = payload
        .template
        .get("version")
        .and_then(Value::as_str)
        .unwrap_or("v1")
        .to_string();
    let context_keywords = extract_string_array(&payload.template, "context_keywords");
    let context_keyword_hits = context_keywords
        .into_iter()
        .filter(|keyword| payload.selected_text.contains(keyword))
        .collect::<Vec<_>>();

    RuleAnalysisBasis {
        sample_chars: payload.selected_text.chars().count(),
        sample_lines: payload.selected_text.lines().count(),
        sample_excerpt: payload.selected_text.chars().take(320).collect(),
        primary_scene: payload.primary_scene.clone(),
        sub_scene: payload.sub_scene.clone(),
        template_scene_id,
        template_scene_name,
        template_version,
        template_field_count: fields.len(),
        context_keyword_hits,
        prompt_excerpt: prompt_text.chars().take(320).collect(),
    }
}

/// Builds a local mock rule analysis package when no LLM is available.
///
/// Uses keyword matching, structure detection, and template hints to produce
/// a reasonable analysis result.
pub(crate) fn build_mock_analysis(payload: &AnalyzeRulesRequest) -> RuleAnalysisPackage {
    let fields = extract_fields(&payload.template);
    let prompt_text = build_rule_prompt(payload);
    let analysis_basis = build_rule_analysis_basis(payload, &fields, &prompt_text);
    let mut field_alias_map = extract_header_alias(&payload.template);

    for field in &fields {
        field_alias_map
            .entry(field.clone())
            .or_insert_with(|| vec![field.clone()]);
    }

    let context_keywords = extract_string_array(&payload.template, "context_keywords");
    let hit_count = context_keywords
        .iter()
        .filter(|keyword| payload.selected_text.contains(keyword.as_str()))
        .count();

    let keyword_score = if context_keywords.is_empty() {
        0.58
    } else {
        0.45 + (hit_count as f64 / context_keywords.len() as f64) * 0.48
    };

    let structure_guess = detect_structure_guess(&payload.selected_text);
    let confidence = match structure_guess.as_str() {
        "table_like" => (keyword_score + 0.08).min(0.98),
        "step_sequence" => (keyword_score + 0.05).min(0.98),
        _ => keyword_score.min(0.93),
    };

    let required_roles = extract_string_array(&payload.template, "required_semantic_roles");
    let content_features = extract_string_array(&payload.template, "content_features");
    let validation_rules = extract_string_array(&payload.template, "validation_rules");
    let structure_patterns = extract_string_array(&payload.template, "structure_patterns");

    let fallback_policy = payload
        .template
        .get("fallback_strategy")
        .and_then(|v| v.get("low_confidence"))
        .and_then(Value::as_str)
        .unwrap_or("ask_user_confirm_mapping")
        .to_string();

    let mut notes = vec![
        "current analysis is generated by local mock; configure API key to use online model"
            .to_string(),
        format!(
            "primary_scene={}, sub_scene={}",
            payload.primary_scene, payload.sub_scene
        ),
    ];
    if confidence < 0.72 {
        notes.push("low confidence: please review alias mapping manually".to_string());
    }

    let package = RuleAnalysisPackage {
        scene_id: payload
            .template
            .get("scene_id")
            .and_then(Value::as_str)
            .unwrap_or(&payload.primary_scene)
            .to_string(),
        fields,
        field_alias_map,
        extraction_hints: required_roles
            .into_iter()
            .chain(content_features)
            .chain(structure_patterns)
            .collect(),
        structure_guess,
        constraints: validation_rules.clone(),
        validation_rules,
        fallback_policy,
        confidence,
        notes,
        llm_provider: "local-mock".to_string(),
        analysis_basis,
    };

    enforce_rule_package(payload, package)
}
